### ISSUE TITLE
Prepare new monex release for eXist 5.1.0

### ISSUE THREAD

**Issue by joewiz** [eXist-db/monex#108]
As noted by @duncdrum in the 2019-09-30 Community Call:

> HEAD of monex no longer compatible with 5.0.0, exist 5.1.0 will need accompanying monex release

**Comment by joewiz** [comment]
@duncdrum I notice that the pom [currently](https://github.com/eXist-db/monex/commit/d31d23d663c09b22f631246e01344940e4ff6ced#diff-600376dffeb79835ede4a0b285078036R67) says 5.1.0-SNAPSHOT. I assume I should update this to 5.1.0 for the release targeting 5.1.0, correct?

**Comment by joewiz** [comment]
@duncdrum Just saw your thumbs up - thanks, will do! - but perhaps best to reply with a comment since emoji thingies don't trigger notifications.

**Comment by line-o** [comment]
@joewiz Can this issue be closed?

**Comment by joewiz** [comment]
@line-o Yes, thanks.
