### ISSUE TITLE
How to add or change an Xml namespace in exist / Cannot use 'xmlns' in the name expression

### ISSUE THREAD

**Issue by SnowMakerDemo** [eXist-db/monex#123]
How to add or change an Xml namespace in exists / Cannot use 'xmlns' in the name expression

**Comment by joewiz** [comment]
Is this a monex question? Can you provide more information?

**Comment by SnowMakerDemo** [comment]
update insert  attribute xmlns:qqq {$importTargetNamespace} into $schema

![image](https://user-images.githubusercontent.com/28621460/79821816-44d62380-83c2-11ea-8efb-a71e547c5232.png)

**Comment by joewiz** [comment]
See https://markmail.org/message/mj7ko5gbprpr4e63. For further questions please open a new issue in the eXist repo or, better yet for XQuery questions (this isn’t a bug), write to the exist-open mailing list or Slack channel. See links in the eXist repo’s README.

**Comment by SnowMakerDemo** [comment]
thank you
