### ISSUE TITLE
Data Visualizer considered harmful

### ISSUE THREAD

**Issue by craigberry** [eXist-db/monex#127]
**Describe the bug**
I was using monex to monitor the performance of a sluggish application.  Among the monex left menu choices, I looked at monitoring, and the console (because the app prints a few key performance measures to the console), and then clicked on Data Visualizer (sic), which I had never used before, hoping to find something useful.  It said something about "index mapping" and I didn't know what it was talking about, so I moved on, but noticed that performance went from a little slow to quite horrible (minutes to get a response from queries that normally take milliseconds or seconds).

Eventually I discovered that simply clicking "Data Visualizer" immediately triggered a run of /db/apps/monex/modules/index2json.xql and passed "/db/apps" as the collection.  As far as I can see after looking at the XQL and the way it calls util:index-keys, that means it's going to try to count all of the nodes in the structural index by document for every collection under /db/apps.  

The problem is, in one of my collections, I have tens of thousands of documents with tens of millions of nodes in the structural index (i.e., they have xml:id present).  A recursive scan of all of those nodes basically locked up my production system with one mouse click.  I attempted to kill the query running index2json.xql (in Monex) but after many hours it is still running and consuming 100% of one CPU on a 4-processor system.  Since eXist is mostly single-threaded, any user query has to compete with that process that has the CPU pegged, thus explaining why things that should take milliseconds now take minutes.

**Expected behavior**
Don't make a self-inflicted DOS attack easier for the user than the alternatives. Specifically, when the user chooses "Data Vizualizer," don't do *anything* until the user specifies what s/he wants to visualize, and perhaps explain the implications of touching every node in the structural index of every collection under /db/apps.

**To Reproduce**
Choose "Data Visualizer" in Monex in any eXist instance that actually has a lot of data to visualize.  "A lot" is relative, but tens of millions of nodes definitely brings things to a virtual halt.

**Context (please always complete the following information):**
eXist 5.2.0. Nothing else in this section is relevant.

**Comment by joewiz** [comment]
@windauer Could you confirm if you were the original contributor of the "Data Visualizer" pane to monex? I traced its appearance in the repository here to https://github.com/eXist-db/monex/pull/1.

**Comment by windauer** [comment]
@joewiz yes I have initialy contributed the "Data Visualizer". To be honest I haven't used the feature in the past years at all so perhaps the easiest would to simply drop it? Otherwise I do like the idea of @craigberry to not start the execution of the index2json script when clicking in the menu but to have an extra button on that side + a warning to not execute this on an online production system...

**Comment by joewiz** [comment]
@windauer Thank you!

As discussed on the community call, we are in favor of removing it for the next release.
