### ISSUE TITLE
[BUG] Monex 3.0.2 refuses to install from the package manager's list

### ISSUE THREAD

**Issue by lguariento** [eXist-db/monex#146]
It is not possible to update / install Monex when clicking on the 'install' icon in the list of available packages or when updating an existing installation of Monex (say 2.x).

**Expected behavior**
I'd expect to install Monex when clicking on the install package icon from the package manager.

**To Reproduce**
Go to the package manager where there's an old version of Monex, click 'update'. Or go to the "available packages" tab, click on the install icon in the Monex box. Threre'll be a 'package installed' message, although the package will not be installed.

logs:

```
2021-03-11 21:48:03,567 [qtp1853015270-92] ERROR (Deploy.java [installAndDeploy]:215) - Failed to install dependency from http://exist-db.org/exist/apps/public-repo/modules/find.xql?name=http%3A%2F%2Fexist-db.org%2Fapps%2Fmonex&processor=5.3.0-SNAPSHOT&version=3.0.2: Read timed out 
java.io.IOException: Failed to install dependency from http://exist-db.org/exist/apps/public-repo/modules/find.xql?name=http%3A%2F%2Fexist-db.org%2Fapps%2Fmonex&processor=5.3.0-SNAPSHOT&version=3.0.2: Read timed out
```

The package is installed correctly when uploading the .xar downloaded from GitHub.

For this test I used eXist-db snapshot of 10 March 2021.

**Comment by joewiz** [comment]
@lguariento I was not able to reproduce this. My steps:

1. Wipe the eXist data directory
2. Start eXist 5.2.0 stable, which installs monex 2.1.1 during startup
3. Quit eXist 5.2.0
4. Start eXist 5.3.0-SNAPSHOT (develop built 10 March 2021)
5. Go to Package Manager, accept prompt to update to monex 3.0.2. 

There were no errors, and monex works. Similarly, downloading monex 3.0.2 from [monex's public-repo](https://exist-db.org/exist/apps/public-repo/packages/monex.html?eXist-db-min-version=5.3.0-SNAPSHOT) page works.

Reviewing what you pasted in from exist.log, it says that the error was:

> Read timed out

Perhaps there was a temporary network issue affecting your internet access or exist-db.org, causing a delay that triggered a time out.

**Comment by lguariento** [comment]
I think we can safely conclude that it was a temporary bottleneck of my own connection, since the error is not happening any more.
