### ISSUE TITLE
[BUG] facets might be displayed incorrectly

### ISSUE THREAD

**Issue by line-o** [eXist-db/monex#165]
**Describe the bug**

The display of elements that are in a facet (or dimension) might be incorrect. The count for each entry might be incorrect.
This can lead to confusion as monex is used as a tool to check if indices of a collection  are set up properly.

**Expected behavior**

A complete list of elements present in a facet each with the correct count.

**To Reproduce**

Set up a collection with at least on facet and one field on an QName. The field must not be present on every element that is indexed. 

Open the index view in Monex. Navigate to the facet of said collection. The elements in this facet is reduced to those that _also_ have the field.

Reason is:

The link is constructed with the fields parameter populated. In the code this triggers the search options to include those fields.
This then excludes all entries from being returned in the result that do not have an entry in the sparse field.

Example link:
```
http://localhost:8080/exist/apps/monex/facet.html?
  collection=/db/lucenetest&
  facet=place&
  fields=place,from,to,date,time,datetime,likes,score&
  node-name=letter
```

**Screenshots**
![Screenshot 2021-11-25 at 14 17 14](https://user-images.githubusercontent.com/657222/143449511-b86bc123-3b70-419e-af47-652579afd50c.png)

**Minimal Test-Setup**

```xquery
(:
 : eXist-db Open Source Native XML Database
 : Copyright (C) 2001 The eXist-db Authors
 :
 : info@exist-db.org
 : http://www.exist-db.org
 :
 : This library is free software; you can redistribute it and/or
 : modify it under the terms of the GNU Lesser General Public
 : License as published by the Free Software Foundation; either
 : version 2.1 of the License, or (at your option) any later version.
 :
 : This library is distributed in the hope that it will be useful,
 : but WITHOUT ANY WARRANTY; without even the implied warranty of
 : MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 : Lesser General Public License for more details.
 :
 : You should have received a copy of the GNU Lesser General Public
 : License along with this library; if not, write to the Free Software
 : Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 :)
(:
 : stripped-down version of facets.xql with a field index configured that is only present in 
 : some of the matching elements (//letter/dateTime).
 :)
xquery version "3.1";

declare variable $local:XML :=
    <letters>
        <letter>
            <place>Berlin</place>
            <dateTime>1972-06-08T10:00:00-05:00</dateTime>
        </letter>
        <letter>
            <place>Berlin</place>
            <dateTime>1970-07-03T00:00:00-05:00</dateTime>
        </letter>
        <letter>
            <place>Hamburg</place>
        </letter>
        <letter>
            <place></place>
        </letter>
        <letter>
            <place>Wrocław</place>
        </letter>
        <letter>
            <place>Wrocław</place>
        </letter>
    </letters>;

declare variable $local:XCONF1 :=
    <collection xmlns="http://exist-db.org/collection-config/1.0">
        <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <lucene>
                <analyzer class="org.exist.indexing.lucene.analyzers.NoDiacriticsStandardAnalyzer" id="nodiacritics"/>
                <text qname="letter" analyzer="nodiacritics">
                    <facet dimension="place" expression="place"/>
                    <field name="dateTime" expression="dateTime" type="xs:dateTime"/>
                </text>
            </lucene>
        </index>
    </collection>;

declare
function local:setup() {
    let $testCol := xmldb:create-collection("/db", "lucenetest")
    let $confCol := xmldb:create-collection("/db/system/config/db", "lucenetest")
    return (
        xmldb:store($confCol, "collection.xconf", $local:XCONF1),
        xmldb:store($testCol, "test.xml", $local:XML),
        xmldb:reindex($personsCol)
    )
};

local:setup()
```

**Context (please always complete the following information):**
 - OS: OSX 10.15.7
 - eXist-db Version: 5.3.0
 - Java Version: AdoptOpen JDK 8
-  App Version: 3.0.3

**Additional context**
- How is eXist-db installed? built from source (eXist-5.3.0)
- Any custom changes in e.g. `conf.xml`? none

**Comment by joewiz** [comment]
Thanks, Juri! I wasn't aware of this issue, and I'd like to be able to better understand your report and the fix in #166. Ideally, I could set up the `/db/lucenetest` collection with the same data and `xconf` file used to see exactly what you're seeing. Would that be possible?

**Comment by line-o** [comment]
@joewiz Of course, I'll add the setup to the issue description

**Comment by joewiz** [comment]
@line-o Thank you! The "Minimal Test-Setup" perfectly illustrates the problem.
