### ISSUE TITLE
[BUG] GitHub Actions CI runs are failing

### ISSUE THREAD

**Issue by joewiz** [eXist-db/monex#179]
Alas, I was wrong in https://github.com/eXist-db/monex/pull/172#issuecomment-1020753132 when I said:

> I seem to recall that the important CI runs here ("push") are passing - and that the failing ones ("pull_request") won't matter once the PR is merged.

I'd be grateful for any insights into what is causing this pattern with master:

> <img width="490" alt="Screen Shot 2022-01-31 at 10 53 30 PM" src="https://user-images.githubusercontent.com/59118/151910513-af0cbc5e-e0d8-4afb-8625-72ea25c6e2d2.png">

**Comment by duncdrum** [comment]
https://github.com/eXist-db/monex/blob/4ce81cc8232ea7cff08f5055b2c6d5c993d8b6ef/pom.xml#L51-L52 is not aligned with https://github.com/eXist-db/monex/blob/4ce81cc8232ea7cff08f5055b2c6d5c993d8b6ef/pom.xml#L321

**Comment by joewiz** [comment]
@duncdrum Thanks! We came to a similar conclusion during today's call. We noticed a new failure, though, in the dependabot PR where exist.processor.version was raised to 6.0.1 - https://github.com/eXist-db/monex/pull/182. @adamretter suggested that we try switching the `console:log` test query from eXide's execute endpoint to eXist's REST endpoint. After testing that locally and finding it passed, I committed it atop the dependabot 6.0.1 PR branch, and it is now passing too.

Do you suggest that I also increment exist.java-api.version to 6.0.1? 

(I have to admit, I'm not clear why show 2 different versions of eXist in the pom. Particularly given the degree to which the jackson libraries requires monex to be in lock step with eXist, it seems rather unrealistic that we would want monex to run on an older version of eXist than we are building it for.)

**Comment by joewiz** [comment]
Or perhaps we should only increment both to 5.4.1 - since 5.4.1 and 6.0.1 are, in fact, on the same version of eXist. 

Again, I don't have a good understanding of the underlying strategy for these two eXist values.

**Comment by duncdrum** [comment]
@joewiz i m not sure what we gain by switching to the rest endpoint, since the console page of monex will still point to db/apps/…    The current test code checks that both the page is loading, and that the endpoint is connecting properly. 

I’m can’t speak for @adamretter

**Comment by joewiz** [comment]
@duncdrum Besides switching from eXide to REST, my commit also introduced some extra checks and delays - https://github.com/eXist-db/monex/pull/182/commits/73344ac9ab9956964c62e37c9598401d320c931d#diff-0c6fb1a95b251215e5df936cbdeff625968e72a66b4119589a1a1a2c91aa8824R53-R54 - which I think may actually have been essential to getting CI to work, even with the switch to 6.0.1. On my localhost, before this addition, tests passed and failed intermittently, but now they just pass.

Since CI is green I'll merge the PR now, but I would gladly welcome opinions on the strategy behind exist.java-api.version vs. exist.processor.version - in terms other than the inline comments, since they still leave me wondering.

**Comment by joewiz** [comment]
Drat. The PR passed CI, but the merge failed. I'll try a pair of PRs - one reverting both exist.java-api.version vs. exist.processor.version to 5.4.1 and one advancing both to 6.0.1.

**Comment by joewiz** [comment]
Also, monex builds are slooooooooow.

**Comment by joewiz** [comment]
In local tests of my 6.0.1-bound build, the first run failed, but the 2nd, 3rd, 4th, and 5th passed. Then the 6th failed. 

So I added `Cypress._.times(10, () => { }` around the block of tests that were failing. (I found this incantation here: https://stackoverflow.com/a/68019476/659732.)

The result is that of 10 iterations of the same test, 7 passed and 3 failed:

```
    remote console
      ✓ should load remote dev console (1518ms)
      ✓ should show log message (2594ms)
    remote console
      ✓ should load remote dev console (1514ms)
      ✓ should show log message (2543ms)
    remote console
      ✓ should load remote dev console (1507ms)
      ✓ should show log message (2549ms)
    remote console
      ✓ should load remote dev console (1504ms)
      1) should show log message
    remote console
      ✓ should load remote dev console (1552ms)
      ✓ should show log message (2588ms)
    remote console
      ✓ should load remote dev console (1520ms)
      ✓ should show log message (2556ms)
    remote console
      ✓ should load remote dev console (1513ms)
      2) should show log message
    remote console
      ✓ should load remote dev console (1540ms)
      3) should show log message
    remote console
      ✓ should load remote dev console (1578ms)
      ✓ should show log message (2575ms)
    remote console
      ✓ should load remote dev console (1521ms)
      ✓ should show log message (2617ms)
```

Repeating the same 10 iterations on the 5.4.1-bound build, again, 7 passed and 3 failed - though they failed on different runs:

```
    remote console
      ✓ should load remote dev console (1576ms)
      ✓ should show log message (2655ms)
    remote console
      ✓ should load remote dev console (1541ms)
      1) should show log message
    remote console
      ✓ should load remote dev console (1588ms)
      ✓ should show log message (2579ms)
    remote console
      ✓ should load remote dev console (1542ms)
      2) should show log message
    remote console
      ✓ should load remote dev console (1578ms)
      ✓ should show log message (2615ms)
    remote console
      ✓ should load remote dev console (1531ms)
      ✓ should show log message (2562ms)
    remote console
      ✓ should load remote dev console (1578ms)
      3) should show log message
    remote console
      ✓ should load remote dev console (1615ms)
      ✓ should show log message (2585ms)
    remote console
      ✓ should load remote dev console (1532ms)
      ✓ should show log message (2592ms)
    remote console
      ✓ should load remote dev console (1538ms)
      ✓ should show log message (2736ms)
```

This suggests that there is some factor - time? websockets? jackson? cypress? - which is leading to intermittent and unpredictable failures when loading the Remote Console tab.

In CI, both the 5.4.1-bound build (https://github.com/eXist-db/monex/pull/183) and the 6.0.1-bound build (https://github.com/eXist-db/monex/pull/184) passed though. 

For now, it seems we're counting on the luck of the draw.

**Comment by joewiz** [comment]
Locally, under the 6.1.0-SNAPSHOT-bound build (#190), with my 10x iterations of the tests as in the last post, I am still seeing the intermittent failures. 

Whether CI passes or fails seems to be the flip of a coin. 

Very strange.

**Comment by duncdrum** [comment]
The most recent commits upgraded a number of components, including cypress and the tricky slf… library. 

Do you still see flaky tests? Build should be faster now as well

**Comment by joewiz** [comment]
@duncdrum You're right! Builds are now green in master. Phew!
