### ISSUE TITLE
Investigate issues with v3.0.5 release, prepare v3.0.6

### ISSUE THREAD

**Issue by joewiz** [eXist-db/monex#217]
v3.0.5 was released but the pom.xml file [still reads](https://github.com/eXist-db/monex/blob/1b5ca7a7b7416d4c112c23bdb681dde8b265ccfa/pom.xml#L15) 3.0.5-SNAPSHOT, and release notes [are missing](https://github.com/eXist-db/monex/blob/4bebd908888b9c0dc5fe1ce7118ffdbc4430cdae/xar-assembly.xml#L243-L248). 

We should investigate what happened with this release and then prepare a new version with release notes and an updated pom, etc.

**Comment by adamretter** [comment]
@joewiz The `pom.xml` file should now be correct, I simply hadn't finished the process.

Regards the release notes in the `xar-assembly.xml`, I was not aware of those. Are they meant to be auto-generated? If not, we should probably document what the release process is for Monex in the `README.md`.
As otherwise a developer who is unaware of any manual steps that are needed needed (like myself), will see a Maven project and run the standard Maven commands to do a release, i.e. `mvn release:prepare && mvn release:perform`

**Comment by line-o** [comment]
The tests do not pass. There is one failing cypress test.
Also the changes were merged by the committer by the looks of things. That is alarming even if it is just a very small change.

**Comment by line-o** [comment]
Why was there a release from a hot fix branch in the first place?
Is this release compatible with older versions of exist?

**Comment by line-o** [comment]
related issue https://github.com/eXist-db/exist/pull/4622

**Comment by adamretter** [comment]
> The tests do not pass. There is one failing cypress test.

The tests were failing due to an unrelated reason to these changes. The reason that they failed is that there was a bad Docker image for the `latest` tag that was being downloaded. I fixed that by uploading the correct Docker image to Docker Hub.

**Comment by adamretter** [comment]
> Why was there a release from a hot fix branch in the first place?

That is the only way you can create a hotfix release after the main branch has moved on from the previous release tag!

> Is this release compatible with older versions of exist, since this version already includes the update to slf4japi?

Yes. The hotfix release does not include the update to `slf4japi` - please check the commit history of the tag if you are uncertain about that.

**Comment by duncdrum** [comment]
> > The tests do not pass. There is one failing cypress test.
> 
> The tests were failing due to an unrelated reason to these changes. The reason that they failed is that there was a bad Docker image for the `latest` tag that was being downloaded. I fixed that by uploading the correct Docker image to Docker Hub.

How was that? The images are automatically updated from develop. How was the image bad? Could you just have triggered the deploy step on ci, or did you need to do something else ?

**Comment by adamretter** [comment]
> How was that?

@duncdrum I don't know how it got into the bad state

**Comment by line-o** [comment]
@adamretter will we know if it gets into a bad state again?

**Comment by duncdrum** [comment]
@joewiz after the most recent merges, I think we are ready for 3.0.6 which should run on both 5.x and 6.x

**Comment by joewiz** [comment]
Superseded by #210 and #230.
