### ISSUE TITLE
Small textual changes... request

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/monex#51]
We can probable remove text like

> To use this feature you need a version of eXist build after April 10th, 2014. Older versions may work in part.

and

> This feature only works on eXist version 2.2RC2 or higher

**Comment by joewiz** [comment]
In the remote console pane.

**Comment by dizzzz** [comment]
![monitoring_and_profiling_for_exist__monex_](https://user-images.githubusercontent.com/1700062/36994933-f4710b72-20b2-11e8-87e5-76be8694a5c6.png)
