### ISSUE TITLE
console logs entire source for XQuery

### ISSUE THREAD

**Issue by mgraauw** [eXist-db/monex#70]
console:log(...)
logs the function name to console,html when called inside a function in the 'source' column (before line/column).

However, when console:log(...) is called from an XQuery body, the entire XQuery source is logged to the 'source' column - which gives large output for large XQueries.

Just logging the XQuery filename in those cases would be an improvement.

**Comment by line-o** [comment]
@mgraauw can you provide us some more details on your environment. At least, the version of exist-db and monex are needed in order to help you. An small example xquery would be great, too.

**Comment by mgraauw** [comment]
This has been a while - I had some 5.x eXist then, which I don't have now - still have 2.2 but I don't expect fixes there. I'll close the issue.

**Comment by joewiz** [comment]
It’s a valid issue that I’d like to keep open. It still affects current versions of exist and monex. Thanks.

**Comment by line-o** [comment]
This is likely the code that needs to be adapted

https://github.com/eXist-db/monex/blob/master/src/main/java/org/exist/console/xquery/Log.java#L190

**Comment by line-o** [comment]
The upcoming version of monex 3.0.0 will have this fixed.

**Comment by line-o** [comment]
e92814c3c47568d21d406e4347cf552402df89ef

**Comment by line-o** [comment]
Now that 3.0.0 is released this needs to be retested and can hopefully closed afterwards.
