### ISSUE TITLE
remove / rewrite hipchat module

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/monex#71]
monex has a hipchat module at `monex/src/main/xar-resources/modules/hipchat.xql` 
rewrite for slack, delete, keep ?

see exist-db/exist#2475

**Comment by joewiz** [comment]
Direct link: https://github.com/eXist-db/monex/blob/master/src/main/xar-resources/modules/hipchat.xql

HipChat is discontinued, so this module cannot be used anymore. The API for other services is certainly different, so I agree this would need to be rewritten if anyone wants the same functionality with a different service like Slack, Rocket.Chat, etc.

I say we remove it, and anyone can consult the repo's history to find the last working code.
