### ISSUE TITLE
Can't install monex in eXist 5.0.0-RC*

### ISSUE THREAD

**Issue by joewiz** [eXist-db/monex#73]
As reported in exist-open (https://markmail.org/message/nlhzzsojc44bjvgi), eXist-5.0.0-RC* is unable to install the current version of monex (v0.9.17) because monex has a dependency on eXist, expressed as `semver-min="5.0.0-SNAPSHOT"` (see https://github.com/eXist-db/monex/blob/master/pom.xml#L66). According to semver 2.0 precedence rules for pre-release metadata (see https://semver.org/#spec-item-11), `5.0.0-RC < 5.0.0-SNAPSHOT` because R comes before S, "lexically in ASCII sort order". Generally, it's bad practice to target pre-release versions, but a workaround would be for us to release a new version of monex with semver-min="5.0.0-R" (which would be `<` all RC and SNAPSHOT versions).  

The goal would be to push out a new release of monex out soon so users of eXist-5.0.0-RC* can install a working version of monex - and so future releases can ship with one.

**Comment by joewiz** [comment]
Comments welcome about the approach proposed here:

> release a new version of monex with semver-min="5.0.0-R" (which would be `<` all RC and SNAPSHOT versions)

**Comment by adamretter** [comment]
Maybe best to choose the lowest RC version where it works... "RC1" perhaps?

**Comment by joewiz** [comment]
That makes sense.

p.s. This makes me yearn for a more expressive notation for expressing ranges. What we really need is `>=5.0.0-RC1 || 5.0.0-SNAPSHOT` (using the NPM semver package's range syntax: https://github.com/npm/node-semver#ranges).

p.p.s. Hopefully we won't have more than 4 more RCs, because `RC10 < RC2`. Maybe next time we should start off with `RC.1` to ensure numeric sorting.

**Comment by duncdrum** [comment]
how about `semver-min="4.999.999"` this gives us room for RC10. I would also suggest a new release to incorporate my last set of fixes

**Comment by duncdrum** [comment]
so #75 fixes bugs in both 0.9.16 (aka `4.x`) and  0.9.17 (aka `5.x`) but I have no means of porting them without breaking sem-ver. 

To fix this we should remove `0.9.17` from public repo and re-release that as `0.10.0` with my fixes making it `0.10.1`, while the same fixes should be ported to 4.x as `0.9.18` to avoid confusion with the just removed `0.9.17`

**Comment by joewiz** [comment]
@duncdrum raises a good point.

We'll need new branches for the 4.x and 5.x line of development. How about this: For simplicity’s sake and alignment with Dashboard, we call the eXist 4.x-bound line Monex 1.x and the eXist 5.x-bound line Monex 2.x. Monex is mature enough to consider it a stable API, and thus deserves a major release instead of forever `0.x` prefixes. Then `develop` will be the `2.x` branch and `develop-1.x` branch will be the `1.x` branch. Then, if eXist 6 is the stable release and introduces breaking changes for Monex, we can initiate a `develop-2.x` branch for the eXist 5.x-bound line, and develop will then be for 6.x-bound work. Sound good?

**Comment by joewiz** [comment]
The work proposed here is complete. I'll prepare releases of the two new versions now.
