### ISSUE TITLE
index browser is missing mock indexes

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/monex#78]
index browser had some test indexes that we used for … testing, they are missing in monex 2.0.0
![Screenshot 2019-04-24 at 14 27 56](https://user-images.githubusercontent.com/6205362/56659465-7b893900-669d-11e9-9ed5-7fdeaf6733ab.png)

```
1) Monex indexes should load Browse Indexes:
     CypressError: Timed out retrying: Expected to find content: '/db/apps/mone
x/indexes-test' but never did.
```

**Comment by joewiz** [comment]
Strange, https://github.com/eXist-db/monex/tree/master/src/main/xar-resources/indexes-test and https://github.com/eXist-db/monex/blob/master/src/main/xar-resources/pre-install.xql#L31-L34 show that the resources in question are present in the repo and are properly placed when the xar is installed...

**Comment by duncdrum** [comment]
after a bit of digging, `collection.xconf` files are copied to `system/db/apps/**/...` as expected for docs,  exide,  etc so `pre-install.xql` are processed as expected for other apps.  

there are no indexes (test or normal) for monex,  which explains why my frontend branch is so sluggish.

there are no errors in the logs when installing the xar (this might be a separate bug) the only messages in the logs:
```
26 Apr 2019 13:16:36,118 [qtp2013332834-260] WARN  (IndexKeys.java [eval]:154) - org.exist.storage.structural.NativeStructur
alIndexWorker isn't an instance of org.exist.indexing.OrderedIndexWorker. Start value '()' ignored.
26 Apr 2019 13:16:37,439 [qtp2013332834-212] WARN  (IndexKeys.java [eval]:154) - org.exist.storage.structural.NativeStructur
alIndexWorker isn't an instance of org.exist.indexing.OrderedIndexWorker. Start value '()' ignored.
```
